import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NotificationBellLoader from "@/components/NotificationBellLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {children}
        {/* Fixed/floating so it doesn't require touching every page's own header. */}
        <div style={{ position: 'fixed', top: 10, right: 10, zIndex: 1000 }}>
          <NotificationBellLoader />
        </div>
      </body>
    </html>
  );
}
